Repository OpenAngelArena/oaa, pull requests merged in 2018-09, with the labels that each got.

#2390 Bottles for contributors
  content/panorama/images/items/custom/bottles/bottle_obby.png
  content/panorama/styles/custom_game/hero_selection.css
  game/scripts/vscripts/components/bottlepass/special_rewards.lua
Labels: Icon

#2383 Rebalance Armlet
  game/scripts/npc/items/item_armlet.txt
  game/scripts/npc/items/item_armlet_2.txt
  game/scripts/npc/items/item_armlet_3.txt
  game/scripts/npc/items/item_armlet_4.txt
  game/scripts/npc/items/item_armlet_5.txt
Labels: Balance, merge after tournament

#2404 Install Doc Update
  docs/git/github-for-noobs.md
  docs/setup/install.md
Labels: Documentation

#2346 Mirana piercing arrow talent
  game/resource/English/ability/units/tooltip_mirana_arrow_oaa.txt
  game/resource/English/ability/units/tooltip_mirana_talents.txt
  game/scripts/npc/abilities/mirana_arrow_oaa.txt
  game/scripts/npc/abilities/mirana_talents.txt
  game/scripts/npc/heroes/mirana.txt
  game/scripts/npc/npc_abilities_custom.txt
  game/scripts/npc/npc_heroes_custom.txt
  game/scripts/vscripts/abilities/oaa_mirana_arrow.lua
  game/scripts/vscripts/libraries/talents/talents_server.lua
Labels: merge after tournament

#2389 Re-add Tinker with infinite channel ult
  game/resource/English/ability/units/tooltip_oaa_rearm.txt
  game/scripts/npc/abilities/tinker_rearm.txt
  game/scripts/npc/herolist.txt
  game/scripts/vscripts/abilities/oaa_rearm.lua
Labels: merge after tournament
