Repository OpenAngelArena/oaa, pull requests merged in 2018-07, with the labels that each got.

#2248 Save/load state
  .luacheckrc
  game/scripts/vscripts/components/boss/spawn.lua
  game/scripts/vscripts/components/bottlepass/server.lua
  game/scripts/vscripts/components/capturepoints/capturepoints.lua
  game/scripts/vscripts/components/creeps/spawner.lua
  game/scripts/vscripts/components/gold/gold.lua
  game/scripts/vscripts/components/index.lua
  game/scripts/vscripts/components/points/points.lua
  game/scripts/vscripts/components/saveload/heroes.lua
  game/scripts/vscripts/components/saveload/index.lua
  game/scripts/vscripts/components/saveload/saveload.lua
  game/scripts/vscripts/components/saveload/wards.lua
  game/scripts/vscripts/components/statprovider/timer.lua
  game/scripts/vscripts/gamemode.lua
  game/scripts/vscripts/internal/gamemode.lua
  game/scripts/vscripts/modifiers/modifier_xpm_thinker.lua
  game/scripts/vscripts/settings.lua
Labels: Enhancement

#2275 Tier 5 Boss Minimap Icon
  content/materials/vgui/hud/minimap_boss_tier5.png
  content/materials/vgui/hud/minimap_boss_tier5.vmat
  game/resource/English/npc/npc_bulidings.txt
  game/scripts/addon_hud_textures.txt
  game/scripts/npc/units/minimap/minimap.txt
  game/scripts/vscripts/components/minimap/minimap_camps.lua
Labels: Icon

#2288 Icon Fix
  game/scripts/addon_hud_textures.txt
Labels: Icon

#2322 Replace Covfefe
  game/resource/English/ability/items/tooltip_trumps_fist.txt
  game/resource/flash3/images/items/custom/trumps_fists.png
  game/resource/flash3/images/items/custom/trumps_fists_2.png
  game/resource/flash3/images/spellicons/custom/trumps_fists.png
  game/resource/flash3/images/spellicons/custom/trumps_fists_2.png
Labels: Icon, Tooltips
