Repository OpenAngelArena/oaa, pull requests merged in 2020-05, with the labels that each got.

#2926 Upgraded Power Treads buffs
  game/scripts/npc/items/farming/item_greater_power_treads.txt
  game/scripts/npc/items/farming/item_greater_power_treads_2.txt
  game/scripts/npc/items/farming/item_greater_power_treads_3.txt
  game/scripts/npc/items/farming/item_greater_power_treads_4.txt
Labels: Balance, Enhancement

#2925 Bug Fixes and Optimisation
  content/panorama/layout/custom_game/custom_ui_manifest.xml
  game/itembuilds/default_abaddon.txt
  game/itembuilds/default_abyssal_underlord.txt
  game/itembuilds/default_alchemist.txt
  game/itembuilds/default_bristleback.txt
  game/itembuilds/default_broodmother.txt
  game/itembuilds/default_dark_willow.txt
  game/itembuilds/default_dazzle.txt
  game/itembuilds/default_doom_bringer.txt
  game/itembuilds/default_dragon_knight.txt
  game/itembuilds/default_drow_ranger.txt
  game/itembuilds/default_earth_spirit.txt
  game/itembuilds/default_earthshaker.txt
  game/resource/English/ability/items/tooltip_force_boots.txt
  game/resource/English/ability/items/tooltip_havoc_hammer.txt
  game/resource/English/ability/items/tooltip_illusionist_cape.txt
  game/resource/English/ability/items/tooltip_imp_claw.txt
  game/resource/English/ability/items/tooltip_magic_lamp.txt
  game/scripts/npc/abilities/neutrals/ghost_frostburn_oaa.txt
  game/scripts/npc/items/item_bloodthorn_5.txt
  game/scripts/npc/items/item_echo_sabre_5.txt
  game/scripts/npc/items/item_force_boots.txt
  game/scripts/npc/items/item_greater_crit_5.txt
  game/scripts/npc/items/item_havoc_hammer.txt
  game/scripts/npc/items/item_havoc_hammer_2.txt
  game/scripts/npc/items/item_heavens_halberd_5.txt
  game/scripts/npc/items/item_illusionsts_cape.txt
  game/scripts/npc/items/item_imp_claw.txt
  game/scripts/npc/items/item_imp_claw_2.txt
  game/scripts/npc/items/item_magic_lamp.txt
  game/scripts/npc/items/item_nullifier_5.txt
  game/scripts/npc/npc_abilities_override.txt
  game/scripts/npc/units/misc/npc_dota_core_guy.txt
  game/scripts/shops/10v10_shops.txt
  game/scripts/shops/ardm_shops.txt
  game/scripts/shops/captains_mode_shops.txt
  game/scripts/shops/oaa_shops.txt
  game/scripts/shops/oaa_test_shops.txt
  game/scripts/shops/oaa_winter_shops.txt
  game/scripts/vscripts/abilities/boss_regen.lua
  game/scripts/vscripts/abilities/boss_resistance.lua
  game/scripts/vscripts/abilities/neutrals/oaa_ghost_frostburn.lua
  game/scripts/vscripts/components/creeps/creep_kill_bounty.lua
  game/scripts/vscripts/components/filters/bottlecounter.lua
  game/scripts/vscripts/components/progression/hero_progression.lua
  game/scripts/vscripts/components/runes/runes.lua
  game/scripts/vscripts/items/black_king_bar.lua
  game/scripts/vscripts/items/farming/modifier_creep_assist_gold.lua
  game/scripts/vscripts/items/hand_of_midas.lua
  game/scripts/vscripts/items/ward_stack.lua
  game/scripts/vscripts/modifiers/sparks/modifier_spark_midas.lua
Labels: Bug Fix, Enhancement

#2924 Dagger of Moriah buffs
  game/resource/English/ability/items/transformation/tooltip_dagger_of_moriah.txt
  game/scripts/npc/items/custom/item_dagger_of_moriah.txt
  game/scripts/npc/items/custom/item_dagger_of_moriah_2.txt
  game/scripts/vscripts/items/transformation/dagger_of_moriah.lua
Labels: Balance, Enhancement

#2923 Windranger buffs
  game/scripts/npc/abilities/windrunner_focusfire.txt
  game/scripts/npc/abilities/windrunner_powershot.txt
  game/scripts/npc/abilities/windrunner_windrun.txt
Labels: Balance

#2919 Invoker buffs + Cold Snap nerf
  game/scripts/npc/abilities/invoker_chaos_meteor.txt
  game/scripts/npc/abilities/invoker_cold_snap.txt
  game/scripts/npc/abilities/invoker_deafening_blast.txt
  game/scripts/npc/abilities/invoker_emp.txt
  game/scripts/npc/abilities/invoker_exort.txt
  game/scripts/npc/abilities/invoker_forge_spirit.txt
  game/scripts/npc/abilities/invoker_ghost_walk.txt
  game/scripts/npc/abilities/invoker_ice_wall.txt
  game/scripts/npc/abilities/invoker_quas.txt
  game/scripts/npc/abilities/invoker_sun_strike.txt
  game/scripts/npc/abilities/invoker_tornado.txt
  game/scripts/npc/abilities/invoker_wex.txt
  game/scripts/npc/abilities/talents/invoker_talents.txt
Labels: Balance

#2914 Storm spirit buffs
  game/scripts/npc/abilities/storm_spirit_ball_lightning.txt
  game/scripts/npc/abilities/storm_spirit_static_remnant.txt
  game/scripts/npc/abilities/talents/storm_spirit_talents.txt
Labels: Balance
